torchrun --nproc_per_node=4 /root/workspace/wav2vec2_pretrain.py \
    --output_dir=/root/output_dir \
    --run_name=wav2vec2-pretrain \
    --model_name_or_path=/root/model \
    --preprocessing_num_workers=10 \
    --overwrite_cache=false \
    --cache_dir=false \
    --seed=42 \
    --do_train=true \
    --do_eval=true \
    --do_predict=true \
    --report_to=none \
    --learning_rate=5e-4 \
    --warmup_ratio=0.08 \
    --weight_decay=0.01 \
    --evaluation_strategy=no \
    --save_strategy=no \
    --logging_strategy=steps \
    --fp16=true \
    --dataset_names \
        jp1924/KsponSpeech \
        jp1924/KrespSpeech \
        jp1924/KoreaSpeech \
        jp1924/KconfSpeech \
    --train_dataset_prefix \
        train \
    --valid_dataset_prefix \
        validation \
        dev \
    --test_dataset_prefix \
        eval_clean \
        eval_other \
    --cache_file_name=preprocessor.arrow \
    --cache_dir=/root/.preprocessor_cache_dir